spring:
   datasource:
      datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/lojaDeLivros?useTimezone=true&serverTimezone=UTC
      username: postgres
      password: 123456
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
         